-- NOUVO POS VANILLA — Settings Seed
-- Version: 3

INSERT OR IGNORE INTO settings (key, value) VALUES
  ('business.name', 'NOUVO POS VANILLA'),
  ('business.logo_path', ''),
  ('business.address', ''),
  ('business.phone_1', ''),
  ('business.phone_2', ''),
  ('business.email', ''),
  ('business.website', ''),
  ('business.slogan', ''),
  ('business.currency_symbol', 'Rs.'),
  ('business.currency_code', 'PKR'),
  ('business.tax_rate', '0'),
  ('business.tax_label', 'Tax'),
  ('business.tax_inclusive', 'false'),

  ('receipt.header_line_1', ''),
  ('receipt.header_line_2', ''),
  ('receipt.footer_line_1', 'Thank you for visiting!'),
  ('receipt.footer_line_2', 'Please come again'),
  ('receipt.show_logo', 'true'),
  ('receipt.show_tax', 'true'),
  ('receipt.show_customer', 'true'),
  ('receipt.show_table', 'true'),
  ('receipt.show_order_type', 'true'),
  ('receipt.show_qr', 'false'),
  ('receipt.copies_customer', '1'),
  ('receipt.copies_kitchen', '1'),
  ('receipt.kitchen_show_prices', 'false'),
  ('receipt.width_mm', '80'),
  ('receipt.char_width', '42'),

  ('printer.name', ''),
  ('printer.type', 'thermal'),
  ('printer.connection', 'usb'),
  ('printer.address', ''),
  ('printer.port', '9100'),
  ('printer.width_mm', '80'),
  ('printer.cut_enabled', 'true'),
  ('printer.beep_enabled', 'false'),
  ('printer.open_drawer', 'false'),

  ('order.delivery_charge_default', '0'),
  ('order.delivery_charge_enabled', 'true'),
  ('order.order_types', '["dine_in","takeaway","delivery"]'),
  ('order.default_order_type', 'takeaway'),
  ('order.require_customer_for_delivery', 'true'),
  ('order.require_table_for_dine_in', 'false'),
  ('order.auto_print_on_checkout', 'true'),
  ('order.invoice_prefix', 'INV'),
  ('order.order_prefix', 'ORD'),
  ('order.discount_enabled', 'true'),
  ('order.discount_max_percent', '100'),

  ('system.backup_enabled', 'true'),
  ('system.backup_retention_days', '30'),
  ('system.backup_time', '02:00'),
  ('system.update_channel', 'stable'),
  ('system.auto_check_updates', 'true'),
  ('system.auto_download_updates', 'false'),
  ('system.language', 'en'),
  ('system.theme', 'light'),
  ('system.date_format', 'DD-MM-YYYY'),
  ('system.time_format', '12h'),
  ('system.audit_retention_days', '0');

INSERT OR IGNORE INTO version (version, name) VALUES (3, 'settings_seed');
